name: update

on: workflow_dispatch

env:
  GH_TOKEN: ${{ github.token }}
  BRANCH: ${{ github.head_ref || github.ref_name }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - run: gh repo clone amirouche/amirouche -- --branch $BRANCH
      - run: cd amirouche && make
      - run: cd amirouche && git checkout -b update-$(date --iso=date)
      - run: git config --global user.name "github action update.yml"
      - run: git config --global user.email "<>"
      - run: cd amirouche && git commit -am "Update for $(date --iso=date)"
      - run: cd amirouche && gh pr create --head --fill-first
 
